### ISSUE TITLE
Module name "canvas-long-shadow" has not been loaded yet for context: _

### ISSUE THREAD

**Issue by Elvincth** [jwueller/canvas-long-shadow#2] opened 2016-04-05 10:12 UTC
Uncaught Error: Module name "canvas-long-shadow" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloadedmakeError @ require.js:166localRequire @ require.js:1407handleImage @ Screen1Controller.js?bust=1459850987:44
Navigated to http://appery.io/app/mobile-frame?src=http://appery.io/app/view/a9ec8e5b-16d8-493f-a68a-3128443f2183&type=mobile

**Comment by jwueller** [comment] 2016-04-05 19:57
Can you elaborate on what is happening here? This looks like a problem with the usage of require.js rather than an error caused by this library.

**Comment by Elvincth** [comment] 2016-04-13 09:54
I am using ionic and angularjs I installed require.js

**Comment by jwueller** [comment] 2016-04-14 17:47
Are you sure that this module is actually properly included? This does not appear to be a problem within this library. Could you provide an [SSCCE](http://sscce.org/)?

**Comment by Elvincth** [comment] 2016-04-17 03:05
Actually I am using appery.io as an IDE so will you give it a test?

**Comment by jwueller** [comment] 2016-04-17 07:50
You haven't given me anything to test, yet. I do not own an appery.io account, nor do I plan on buying one. Please provide detailed instructions on how to reproduce the problem.

**Comment by Elvincth** [comment] 2016-04-18 02:56
Make a video showing you all files???

**Comment by jwueller** [comment] 2016-04-19 15:55
I will not be able to determine what the problem might be if there is nothing to test. If you cannot provide a (reproducible) test case, I'll need to close this issue due to lack of information.

**Closed as completed** 2016-05-05 20:14 UTC
